shell = "zsh"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
use = ["zsh-completions.plugin.zsh"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["zsh-autosuggestions.zsh"]
apply = ["defer"]

[plugins.zsh-autosuggestions.hooks]
pre = "ZSH_AUTOSUGGEST_USE_ASYNC=1"

[plugins.zeno]
github = "yuki-yano/zeno.zsh"
branch = "feature/sqlite-history-subsystem"

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
use = ["fast-syntax-highlighting.plugin.zsh"]
apply = ["defer"]
